source 'https://rubygems.org'

gem 'middleman', git: 'git@github.com:middleman/middleman.git', branch: 'v3-stable'
gem 'middleman-livereload', '~> 3.1.0'
gem 'wdm', '~> 0.1.0', :platforms => [:mswin, :mingw]
gem 'compass', '1.0.0.alpha.19'
gem 'compass-placeholders'
gem 'livingstyleguide'
gem 'quotation-marks', path: '..'
gem 'github-badge'

